db:
  host: localhost
  port: 5432
  username: postgres
  password: ''
  name: rosen_service
healthCheck:
  logging:
    maxErrors: 10
    maxWarns: 10
    duration: 100
  scanner:
    warnDiff: 2
    criticalDiff: 10
  updateInterval: 60
chains:
  ergo:
    initialHeight: 1
    scanInterval: 120
    method: explorer
    explorer:
      url: https://api.ergoplatform.com/
  cardano:
    active: false
    initialHeight: 1
    scanInterval: 30
    koios:
      timeout: 100
  bitcoin:
    active: false
    initialHeight: 1
    scanInterval: 600
    rpc:
      timeout: 100
    esplora:
      timeout: 100
  doge:
    active: false
    initialHeight: 1
    scanInterval: 60
    esplora:
      timeout: 100
  ethereum:
    active: false
    initialHeight: 1
    scanInterval: 60
    rpc:
      timeout: 100
  binance:
    active: false
    initialHeight: 1
    scanInterval: 10
    rpc:
      timeout: 100
  bitcoin-runes:
    active: false
    scanInterval: 10
paths:
  tokens: config/rosen/tokensMap.json
  contracts: config/rosen
