db:
  host: localhost
  username: postgres
  password: ''
  name: rosen_service
chains:
  ergo:
    initialHeight: 1578000
    node:
      url: https://node.ergopool.io/
      rescanDelaySeconds: 0
      blockRetrieveGap: 1
  cardano:
    active: false
  bitcoin:
    active: false
  doge:
    active: false
  ethereum:
    active: false
  binance:
    active: false
  runes:
    active: false
