db:
  host: localhost
  port: 5432
  username: postgres
  password: ''
  name: rosen_service
healthCheck:
  logging:
    maxErrors: 10
    maxWarns: 10
    duration: 100
  scanner:
    warnDiff: 2
    criticalDiff: 10
  updateInterval: 60
chains:
  ergo:
    initialHeight: 1
    scanInterval: 60
    method: explorer
    node:
      url: https://node.ergopool.io/
    explorer:
      url: https://explorer.ergoplatform.com/
  cardano:
    active: false
    initialHeight: 1
    scanInterval: 60
    method: koios
    koios:
      timeout: 100
  bitcoin:
    active: false
    initialHeight: 1
    scanInterval: 60
    method: rpc
    rpc:
      timeout: 100
    esplora:
      timeout: 100
  doge:
    active: false
    initialHeight: 1
    scanInterval: 60
    method: rpc
    esplora:
      timeout: 100
  ethereum:
    active: false
    initialHeight: 1
    scanInterval: 60
    rpc:
      timeout: 100
  binance:
    active: false
    initialHeight: 1
    scanInterval: 60
    rpc:
      timeout: 100
  runes:
    active: false
paths:
  tokens: config/rosen/tokensMap.json
  contracts: config/rosen
