db:
  host: localhost
  port: 5432
  username: postgres
  password: ''
  name: rosen_service
healthCheck:
  logging:
    maxErrors: 10
    maxWarns: 10
    duration: 100
  scanner:
    warnDiff: 2
    criticalDiff: 10
  updateInterval: 60
chains:
  ergo:
    initialHeight: 1
    scanInterval: 120
    method: explorer
    explorer:
      connections:
        - url: https://api.ergoplatform.com/
  cardano:
    active: false
    scanInterval: 30
    initialHeight: 1
    koios:
      connections:
        - url: https://api.koios.rest/api/v1/
          timeout: 100
  bitcoin:
    active: false
    initialHeight: 1
    scanInterval: 600
  doge:
    active: false
    initialHeight: 1
    scanInterval: 60
  ethereum:
    active: false
    initialHeight: 1
    scanInterval: 60
  binance:
    active: false
    initialHeight: 1
    scanInterval: 10
  bitcoinRunes:
    active: false
paths:
  tokens: config/rosen/tokensMap.json
  contracts: config/rosen
