chains:
  ergo:
    node:
      url: ''
  cardano:
    koios:
      url: ''
  bitcoin:
    rpc:
      url: ''
  ethereum:
    rpc:
      url: ''
  binance:
    rpc:
      url: ''
paths:
  tokens: tests/config/rosen/tokensMap.json
  contracts: tests/config/rosen
