chains:
  ergo:
    explorer:
      url: ''
  cardano:
    active: false
    koios:
      url: ''
  bitcoin:
    active: false
    rpc:
      url: ''
  ethereum:
    active: false
    rpc:
      url: ''
  binance:
    active: false
    rpc:
      url: ''
paths:
  tokens: tests/config/rosen/tokensMap.json
  contracts: tests/config/rosen
